sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_paypal_admin:
    resource: "@SyliusPayPalPlugin/config/admin_routing.yml"
    prefix: '/%sylius_admin.path_name%'
